# Generated by Django 5.0.6 on 2024-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('moderation_results', models.JSONField(default=list)),
                ('current_node', models.CharField(max_length=100, verbose_name='当前节点')),
                ('conversation_id', models.CharField(max_length=100, verbose_name='对话ID')),
                ('messages', models.JSONField(default=list, verbose_name='对话列表')),
                ('mapping', models.JSONField(verbose_name='对话内容')),
                ('default_model_slug', models.CharField(max_length=100, verbose_name='模型')),
                ('user_id', models.CharField(max_length=100, verbose_name='当前节点')),
            ],
        ),
    ]
